[profile.default]
bytecode_hash = "none"
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
libs = ["lib"]
out = "out"
src = "src"
via_ir = false
optimizer_runs = 44444444
dynamic_test_linking = true

[fmt]
sort_imports = true

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false

[rpc_endpoints]
unichain_sep = "${UNICHAIN_SEPOLIA_URL}"
